google-ID: 'G-99TM6KXFM4'

menu:
- {name: 'Archives', url: 'archives.html'}
- {name: 'About',   url: 'about.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github',     link: 'https://www.github.com/subhashhhhhh'}
- {icon: 'linkedin',   link: 'http://www.linkedin.com/in/subhashgottumukkala/'}
- {icon: 'envelope',   link: 'mailto:subhashgottumukkala17@gmail.com'}
- {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

post_date_prefix: 'Written on'
